# Generated by Django 6.0.6 on 2026-06-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_rename_email_cliente_correo_alter_cliente_nombre_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.AlterModelOptions(
            name="detalleventa",
            options={
                "verbose_name": "Detalle de venta",
                "verbose_name_plural": "Detalles de venta",
            },
        ),
        migrations.AlterModelOptions(
            name="venta",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
            },
        ),
    ]
