# Generated by Django 6.0.6 on 2026-06-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consumomateriaprima",
            options={
                "verbose_name": "Consumo de materia prima",
                "verbose_name_plural": "Consumos de materia prima",
            },
        ),
        migrations.AlterModelOptions(
            name="ordenproduccion",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Orden de producción",
                "verbose_name_plural": "Órdenes de producción",
            },
        ),
        migrations.AlterModelOptions(
            name="productofinal",
            options={
                "verbose_name": "Producto final",
                "verbose_name_plural": "Productos finales",
            },
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="finalizada_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="estado",
            field=models.CharField(
                choices=[("PENDIENTE", "Pendiente"), ("FINALIZADA", "Finalizada")],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
