# Generated by Django 6.0.2 on 2026-03-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovimientoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("EGRESO", "Egreso")],
                        max_length=10,
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("descripcion", models.CharField(max_length=200)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
