# Generated by Django 6.0.6 on 2026-06-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_categoria_descripcion_producto_descripcion_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
    ]
