# Generated by Django 6.0.6 on 2026-07-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_alter_categoria_options_alter_producto_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="precio",
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_costo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Costo de producción o compra al proveedor.",
                max_digits=10,
                verbose_name="Precio de costo",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_venta",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Precio que se cobra al cliente.",
                max_digits=10,
                verbose_name="Precio de venta",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="tipo",
            field=models.CharField(
                choices=[("MP", "Materia Prima"), ("PT", "Producto Terminado")],
                default="MP",
                max_length=2,
                verbose_name="Tipo de producto",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="unidad_medida",
            field=models.CharField(
                choices=[
                    ("UND", "Unidad"),
                    ("PAR", "Par"),
                    ("MET", "Metro"),
                    ("YRD", "Yarda"),
                    ("ROL", "Rollo"),
                    ("LIT", "Litro"),
                    ("GAL", "Galón"),
                    ("KGR", "Kilogramo"),
                    ("DOC", "Docena"),
                ],
                default="UND",
                max_length=3,
                verbose_name="Unidad de medida",
            ),
        ),
    ]
