# Generated by Django 6.0.3 on 2026-03-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proveedor",
            name="email",
        ),
        migrations.AddField(
            model_name="proveedor",
            name="direccion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="contacto",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="telefono",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
