# Generated by Django 6.0.6 on 2026-06-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0002_remove_proveedor_email_proveedor_direccion_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detallecompra",
            options={
                "verbose_name": "Detalle de compra",
                "verbose_name_plural": "Detalles de compra",
            },
        ),
        migrations.AlterModelOptions(
            name="ordencompra",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Orden de compra",
                "verbose_name_plural": "Órdenes de compra",
            },
        ),
        migrations.AlterModelOptions(
            name="proveedor",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
            },
        ),
    ]
