# Generated by Django 6.0.6 on 2026-07-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0003_alter_detallecompra_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordencompra",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("RECIBIDA", "Recibida"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="PENDIENTE",
                max_length=10,
                verbose_name="Estado de la orden",
            ),
        ),
    ]
