# Generated by Django 6.0.3 on 2026-03-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registroauditoria",
            name="descripcion",
        ),
        migrations.AddField(
            model_name="registroauditoria",
            name="detalle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="registroauditoria",
            name="usuario",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
